# Example sensors.yaml demonstrating safe GPIO usage for CC1101.
# Avoid ESP32 boot-strapping pins such as GPIO2 and GPIO15 unless
# external circuitry holds them in safe states during boot.

external_components:
  - source: github://SzczepanLeon/esphome-components@version_4
    refresh: 0d
    components: [ wmbus ]

wmbus:
  mosi_pin: GPIO13
  miso_pin: GPIO12
  clk_pin:  GPIO14
  cs_pin:   GPIO18
  gdo0_pin: GPIO16
  gdo2_pin: GPIO17

  led_pin: GPIO21
  led_blink_time: "1s"

  frequency: 868.950
  all_drivers: False
  sync_mode: True
  log_all: True

sensor:
  - platform: wmbus
    meter_id: 0x04913581
    type: apatorna1
    key: "00112233445566778899AABBCCDDEEFF"
    sensors:
      - name: "apatorna1 water"
        field: "total"
        unit_of_measurement: "m³"
